name: "Ansible security & quality scanner"

on: 
  workflow_call:

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  ansible-security-scan:
    # Run the KICS security scanner against Ansible code
    runs-on: ubuntu-latest
    name: "Ansible Security Scan"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
  
      - name: Run KICS Scan with SARIF result
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
          path: '.'
          output_path: results-dir
          platform_type: ansible
          output_formats: 'json,sarif'
          enable_comments: true
          # ignore_on_exit: results # options: all, results, errors, none
          # fail_on: 'high,medium,low,info' # only relevant when failing the job based on results
      
      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results-dir/results.sarif

  ansible-linter:
    # Run the ansible-lint linter against Ansible code
    runs-on: ubuntu-latest
    name: "Ansible Linter"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.20.3
        with:
          args: "--sarif-file lint-results.sarif -vv"

      - name: pwd script
        if: success() || failure()
        run: pwd
      
      - name: list script
        if: success() || failure()
        run: ls -la

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: lint-results.sarif
