name: "Ansible security & quality scanner"

on: 
  workflow_call:

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  kics-security-scan:
    # Run the KICS security scanner against Ansible code
    runs-on: ubuntu-latest
    name: "Ansible Security Scan"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Run KICS Scan with SARIF result
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
          platform_type: ansible
          output_formats: 'sarif'
          
      - name: Show results
        run: |
          cat results.sarif
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  ansible-lint:
    # Run the ansible-lint linter against Ansible code
    runs-on: ubuntu-latest
    name: "Ansible Linter"
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.20.3
        with:
          args: "--format sarif --sarif-file lint-results.sarif"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lint-results.sarif
